language: python
python:
- "3.6"
install:
- pip install -r requirements.txt
before_script:
 - export SECRET_KEY="secret"
script:
- pytest -v -W error::UserWarning
- coverage run --source=app -m pytest && coverage report
after_success:
- coveralls